twitter:
  consumer_key: '9SFWRrKRh9b2WhwjErrNIjDDN'
  consumer_secret: 'hUU8tkLyBNpvARFVZB4Cde28xIve4HxBAjJLq6yWkeRfvwN45t'
  oauth_token: '3119963958-3qAkO3gaT1Bls5uIYbLmBR2fB6Mh2FTdOEIPdDQ'
  oauth_token_secret: 'HmoT2tbpP74ksXZsvpNgrTJ4YJkjrZFHdfuuSFwIqqo6Q'
proxies: [ #vip.squidproxies.com/api.php?command=list&user=57194&pass=9ypYH5VmScQ
  '173.234.250.69:8800',
  '173.234.250.166:8800',
  '173.208.46.216:8800',
  '173.234.194.242:8800',
  '173.234.194.137:8800',
  '173.234.250.102:8800',
  '173.234.226.60:8800',
  '173.234.226.181:8800',
  '192.161.163.124:8800',
  '170.130.58.170:8800',
  '173.208.46.215:8800',
  '173.234.226.146:8800',
  '173.234.194.4:8800',
  '192.161.163.61:8800',
  '173.234.194.75:8800',
  '170.130.58.197:8800',
  '173.208.46.61:8800',
  '173.208.46.163:8800',
  '192.161.163.115:8800',
  '170.130.58.132:8800',
  '173.234.250.96:8800',
  '192.161.163.210:8800',
  '173.234.226.224:8800',
  '170.130.58.148:8800',
  '192.161.163.243:8800'
]
diffbot:
  token: d423a041afa69fbbaabf912ae1ff068c
createsend:
  api_key: 1e32c5711fd4f497aa248056a6fd4ebe
  client_id: 889dfa38192c39d352717c865594bd8e
linkedin:
  client_id: 7726tj9n6uri0s
  client_secret: Zl7Rsixu7uWVxUjh
  token: b1cf15c4-dfeb-4e93-8016-2802649baab4
  secret: 1546c61c-9c51-4ad1-984d-b26a15e8b57e
angellist:
  token: 6e1cbad61278cdb35b1280369e7f13b9661ee906e829b24b
aws:
  access_key_id: AKIAJNKACBCJNIYL6AKA
  secret_key: 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
categories:
  '01': 'culture & entertainment'
  '01001': 'archaeology'
  '01002': 'architecture'
  '01003': 'bullfighting'
  '01004': 'festive event'
  '01005': 'cinema'
  '01006': 'dance'
  '01007': 'fashion'
  '01008': 'language'
  '01009': 'library and museum'
  '01010': 'literature'
  '01011': 'music'
  '01012': 'painting'
  '01013': 'photography'
  '01014': 'radio'
  '01015': 'sculpture'
  '01016': 'television'
  '01017': 'theatre'
  '01018': 'monument and heritage site'
  '01019': 'customs and tradition'
  '01020': 'arts'
  '01021': 'entertainment'
  '01022': 'culture'
  '01023': 'nightclub'
  '01024': 'cartoon'
  '01025': 'animation'
  '01026': 'mass media'
  '01027': 'internet'
  '01028': 'history'
  '02': 'crime, law & justice'
  '02001': 'crime'
  '02002': 'judiciary'
  '02003': 'police'
  '02004': 'punishment'
  '02005': 'prison'
  '02006': 'laws'
  '02007': 'justice and rights'
  '02008': 'trials'
  '02009': 'prosecution'
  '02010': 'organized crime'
  '02011': 'international law'
  '02012': 'corporate crime'
  '02013': 'war crime'
  '02014': 'inquest'
  '02015': 'inquiry'
  '02016': 'tribunal'
  '03': 'disaster'
  '03001': 'drought'
  '03002': 'earthquake'
  '03003': 'famine'
  '03004': 'fire'
  '03005': 'flood'
  '03006': 'industrial accident'
  '03007': 'meteorological disaster'
  '03008': 'nuclear accident'
  '03009': 'pollution'
  '03010': 'transport accident'
  '03011': 'volcanic eruption'
  '03012': 'relief and aid organisation'
  '03013': 'accident'
  '03014': 'emergency incident'
  '03015': 'disaster'
  '03016': 'emergency planning'
  '03017': 'rescue'
  '04': 'business & finance'
  '04001': 'agriculture'
  '04002': 'chemicals'
  '04003': 'computing and information technology'
  '04004': 'construction and property'
  '04005': 'energy and resource'
  '04006': 'financial and business service'
  '04007': 'consumer goods'
  '04008': 'macro economics'
  '04009': 'market and exchange'
  '04010': 'media'
  '04011': 'manufacturing and engineering'
  '04012': 'metal and mineral'
  '04013': 'process industry'
  '04014': 'tourism and leisure'
  '04015': 'transport'
  '04016': 'company information'
  '04017': 'economy'
  '04018': 'business'
  '04019': 'finance'
  '05': 'education'
  '05001': 'adult education'
  '05002': 'further education'
  '05003': 'parent organisation'
  '05004': 'preschool'
  '05005': 'school'
  '05006': 'teachers union'
  '05007': 'university'
  '05008': 'upbringing'
  '05009': 'entrance examination'
  '05010': 'teaching and learning'
  '05011': 'religious education'
  '06': 'environment'
  '06001': 'renewable energy'
  '06002': 'conservation'
  '06003': 'energy saving'
  '06004': 'environmental politics'
  '06005': 'environmental pollution'
  '06006': 'natural resources'
  '06007': 'nature'
  '06008': 'population'
  '06009': 'waste'
  '06010': 'water'
  '06011': 'global warming'
  '06012': 'hazardous materials'
  '06013': 'environmental cleanup'
  '07': 'health'
  '07001': 'disease'
  '07002': 'epidemic and plague'
  '07003': 'health treatment'
  '07004': 'health organisations'
  '07005': 'medical research'
  '07006': 'medical staff'
  '07007': 'medicine'
  '07008': 'preventative medicine'
  '07009': 'injury'
  '07010': 'hospital and clinic'
  '07011': 'government health care'
  '07012': 'private health care'
  '07013': 'healthcare policy'
  '07014': 'medical specialisation'
  '07015': 'medical service'
  '07016': 'physical fitness'
  '07017': 'illness'
  '07018': 'medical conditions'
  '07019': 'patient'
  '08': 'human interest'
  '08001': 'animal'
  '08002': 'curiosity'
  '08003': 'people'
  '08004': 'mystery'
  '08005': 'society'
  '08006': 'award and prize'
  '08007': 'imperial and royal matters'
  '08008': 'plant'
  '09': 'labour'
  '09001': 'apprentices'
  '09002': 'collective contract'
  '09003': 'employment'
  '09004': 'labour dispute'
  '09005': 'labour legislation'
  '09006': 'retirement'
  '09007': 'retraining'
  '09008': 'strike'
  '09009': 'unemployment'
  '09010': 'unions'
  '09011': 'wage and pension'
  '09012': 'work relations'
  '09013': 'health and safety at work'
  '09014': 'advanced training'
  '09015': 'employer'
  '09016': 'employee'
  '10': 'lifestyle'
  '10001': 'game'
  '10002': 'gaming and lottery'
  '10003': 'gastronomy'
  '10004': 'hobby'
  '10005': 'holiday or vacation'
  '10006': 'tourism'
  '10007': 'travel and commuting'
  '10008': 'club and association'
  '10009': 'lifestyle'
  '10010': 'leisure'
  '10011': 'public holiday'
  '10012': 'hunting'
  '10013': 'fishing'
  '10014': 'auto trends'
  '10015': 'adventure'
  '10016': 'beauty'
  '10017': 'consumer issue'
  '10018': 'wedding'
  '11': 'politics'
  '11001': 'defence'
  '11002': 'diplomacy'
  '11003': 'election'
  '11004': 'espionage and intelligence'
  '11005': 'foreign aid'
  '11006': 'government'
  '11007': 'human rights'
  '11008': 'local authority'
  '11009': 'parliament'
  '11010': 'parties and movements'
  '11011': 'refugee'
  '11012': 'regional authority'
  '11013': 'state budget and tax'
  '11015': 'constitution'
  '11016': 'interior policy'
  '11017': 'migration'
  '11018': 'citizens initiative and recall'
  '11019': 'referenda'
  '11020': 'nuclear policy'
  '11021': 'lobbying'
  '11022': 'regulatory policy and organisation'
  '11023': 'censorship'
  '11024': 'politics'
  '11025': 'freedom of the press'
  '11026': 'freedom of religion'
  '11027': 'treaty'
  '11028': 'international organisation'
  '12': 'belief'
  '12001': 'cult and sect'
  '12002': 'belief'
  '12003': 'freemasonry'
  '12006': 'values'
  '12007': 'church and state relations'
  '12008': 'philosophy'
  '12009': 'christianity'
  '12010': 'islam'
  '12011': 'judaism'
  '12012': 'buddhism'
  '12013': 'hinduism'
  '12014': 'religious festival or holiday'
  '12015': 'religious leader'
  '12016': 'nature religion'
  '12017': 'taoism'
  '12018': 'shintoism'
  '12019': 'sikhism'
  '12020': 'jainism'
  '12021': 'parsasm'
  '12022': 'confucianism'
  '12023': 'religious text'
  '12024': 'interreligious dialogue'
  '12025': 'religious event'
  '12026': 'concordat'
  '12027': 'ecumenism'
  '13': 'science & tech'
  '13001': 'applied science'
  '13002': 'engineering'
  '13003': 'human science'
  '13004': 'natural science'
  '13005': 'philosophical science'
  '13006': 'research'
  '13007': 'scientific exploration'
  '13008': 'space programme'
  '13009': 'science'
  '13010': 'technology'
  '13011': 'standards'
  '13012': 'animal science'
  '13013': 'micro science'
  '13014': 'marine science'
  '13015': 'weather science'
  '13016': 'electronics'
  '13017': 'identification technology'
  '13018': 'mathematics'
  '13019': 'biotechnology'
  '13020': 'agricultural research and technology'
  '13021': 'nanotechnology'
  '13022': 'IT/computer sciences'
  '13023': 'scientific institutions'
  '14': 'social issues'
  '14001': 'addiction'
  '14002': 'charity'
  '14003': 'demographics'
  '14004': 'disabled'
  '14005': 'euthanasia'
  '14006': 'family'
  '14007': 'family planning'
  '14008': 'health insurance'
  '14009': 'homelessness'
  '14010': 'minority group'
  '14011': 'pornography'
  '14012': 'poverty'
  '14013': 'prostitution'
  '14014': 'racism'
  '14015': 'welfare'
  '14016': 'abortion'
  '14017': 'missing person'
  '14018': 'long term care'
  '14019': 'juvenile delinquency'
  '14020': 'nuclear radiation victims'
  '14021': 'slavery'
  '14022': 'abusive behaviour'
  '14023': 'death and dying'
  '14024': 'people'
  '14025': 'social issues'
  '14026': 'ordnance clearance'
  '14027': 'reconstruction'
  '15': 'sports'
  '15001': 'aero and aviation sport'
  '15002': 'alpine skiing'
  '15003': 'American football'
  '15004': 'archery'
  '15005': 'athletics, track and field'
  '15006': 'badminton'
  '15007': 'baseball'
  '15008': 'basketball'
  '15009': 'biathlon'
  '15010': 'billiards, snooker and pool'
  '15011': 'bobsleigh'
  '15012': 'bowling'
  '15013': 'bowls and petanque'
  '15014': 'boxing'
  '15015': 'canoeing and kayaking'
  '15016': 'climbing'
  '15017': 'cricket'
  '15018': 'curling'
  '15019': 'cycling'
  '15020': 'dancing'
  '15021': 'diving'
  '15022': 'equestrian'
  '15023': 'fencing'
  '15024': 'field Hockey'
  '15025': 'figure Skating'
  '15026': 'freestyle Skiing'
  '15027': 'golf'
  '15028': 'gymnastics'
  '15029': 'handball'
  '15030': 'horse racing, harness racing'
  '15031': 'ice hockey'
  '15032': 'Jai Alai (Pelota)'
  '15033': 'judo'
  '15034': 'karate'
  '15035': 'lacrosse'
  '15036': 'luge'
  '15037': 'marathon'
  '15038': 'modern pentathlon'
  '15039': 'motor racing'
  '15040': 'motor rallying'
  '15041': 'motorcycling'
  '15042': 'netball'
  '15043': 'nordic skiing'
  '15044': 'orienteering'
  '15045': 'polo'
  '15046': 'power boating'
  '15047': 'rowing'
  '15048': 'rugby league'
  '15049': 'rugby union'
  '15050': 'sailing'
  '15051': 'shooting'
  '15052': 'ski jumping'
  '15053': 'snow boarding'
  '15054': 'soccer'
  '15055': 'softball'
  '15056': 'speed skating'
  '15057': 'speedway'
  '15058': 'sports organisations'
  '15059': 'squash'
  '15060': 'sumo wrestling'
  '15061': 'surfing'
  '15062': 'swimming'
  '15063': 'table tennis'
  '15064': 'Taekwon-Do'
  '15065': 'tennis'
  '15066': 'triathlon'
  '15067': 'volleyball'
  '15068': 'water polo'
  '15069': 'water skiing'
  '15070': 'weightlifting'
  '15071': 'windsurfing'
  '15072': 'wrestling'
  '15073': 'sports event'
  '15074': 'rodeo'
  '15075': 'mini golf sport'
  '15076': 'bandy'
  '15077': 'flying disc'
  '15078': 'floorball'
  '15079': 'casting'
  '15080': 'tug-of-war'
  '15081': 'croquette'
  '15082': 'dog racing'
  '15083': 'skeleton'
  '15084': 'Australian rules football'
  '15085': 'Canadian football'
  '15086': 'duathlon'
  '15087': 'hornuss'
  '15088': 'fist ball'
  '15089': 'inline skating'
  '15090': 'grass ski'
  '15091': 'snowbiking'
  '15092': 'twirling'
  '15093': 'kendo'
  '15094': 'jukendo'
  '15095': 'naginata'
  '15096': 'kyudo'
  '15097': 'kabaddi'
  '15098': 'sepak takraw'
  '15099': 'wushu'
  '15100': 'darts'
  '15101': 'bodybuilding'
  '15102': 'sports disciplinary action'
  '15103': 'sports awards'
  '16': 'conflict'
  '16001': 'act of terror'
  '16002': 'armed conflict'
  '16003': 'civil unrest'
  '16004': "coup d'etat"
  '16005': 'guerrilla activity'
  '16006': 'massacre'
  '16007': 'riots'
  '16008': 'demonstration'
  '16009': 'war'
  '16010': 'conflict'
  '16011': 'crisis'
  '16012': 'weaponry'
  '17': 'weather'
  '17001': 'forecast'
  '17002': 'global change'
  '17003': 'report'
  '17004': 'statistic'
  '17005': 'warning'
